version: "3.8"

services:
  app:
    image: sm3055/project1
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./upload:/home/ec2-user/app/upload
    environment:
      - com.example.upload.path=/home/ec2-user/app/upload
